### ISSUE TITLE
Example decode wmbus oms packet

### ISSUE THREAD

**Issue by 0x-Fede** [soef/wm-bus#1]
Hi,

I'm trying to decode this packet, previously AES decoded: 

44D3101317050050047AAF0030052F2F0C0600000000046D032C34250C13213300008C4013000000008C804013000000000B3B1300000B2D0000002F2F2F

wmbus.parse('44D3101317050050047AAF0030052F2F0C0600000000046D032C34250C13213300008C4013000000008C804013000000000B3B1300000B2D0000002F2F2F');

Return:

field 52
crc0 3035 calc 32ef
CRC check failed on link layer

Any example of .js for decoding this packet, please ?
Thanks!

**Comment by soef** [comment]
Hi, 

I don't know what the probem is. Where from do you get the data, or what device receives the data? Is the CRC already removed? Who ist the manufacture of the transmittng device? The Manufacture is important for me for further research.

**Comment by 0x-Fede** [comment]
Hi,

The problem is I can't parse wm-bus OMS packet to obtain reading values.

Packet is captured and AES decoded by 2N SmartCOM PRO gateway. https://www.2n.cz/en_GB/products/m2m/2n-smartcom-pro

I think CRCs are already removed by Gateway.

Device is heating meter Sonometer 30 from Danfoss Manufacturer.
http://products.danfoss.com/productrange/documents/heatingsolutions/energy-meters/sonometer-30

Do you have a wm-bus packet example to decode with wmbus.parse('wmbus message'); ¿?

Thanks!

**Comment by 0x-Fede** [comment]
44D3101317050050047AAF0030052F2F0C0600000000046D032C34250C13213300008C4013000000008C804013000000000B3B1300000B2D0000002F2F2F

Wm-bus packet output from another parse tool.

<MBusData>

    <SlaveInformation>
        <Id>51713</Id>
        <Manufacturer>DFS</Manufacturer>
        <Version>80</Version>
        <Medium>Heat</Medium>
        <AccessNumber>175</AccessNumber>
        <Status>00</Status>
        <Signature>0000</Signature>
    </SlaveInformation>

    <DataRecord id="0">
        <Function>Instantaneous value</Function>
        <Unit>Energy (kWh)</Unit>
        <Value>0</Value>
    </DataRecord>

    <DataRecord id="1">
        <Function>Instantaneous value</Function>
        <Unit>Time Point (time &amp; date)</Unit>
        <Value>2017-05-20T12:03:00</Value>
    </DataRecord>

    <DataRecord id="2">
        <Function>Instantaneous value</Function>
        <Unit>Volume (m m^3)</Unit>
        <Value>3321</Value>
    </DataRecord>

    <DataRecord id="3">
        <Function>Instantaneous value</Function>
        <Unit>Volume (m m^3)</Unit>
        <Value>0</Value>
    </DataRecord>

    <DataRecord id="4">
        <Function>Instantaneous value</Function>
        <Unit>Volume (m m^3)</Unit>
        <Value>0</Value>
    </DataRecord>

    <DataRecord id="5">
        <Function>Instantaneous value</Function>
        <Unit>Volume flow (m m^3/h)</Unit>
        <Value>13</Value>
    </DataRecord>

    <DataRecord id="6">
        <Function>Instantaneous value</Function>
        <Unit>Power (100 W)</Unit>
        <Value>0</Value>
    </DataRecord>

</MBusData>

**Comment by soef** [comment]
Hi, 

with the information above I have researched a bit further. The data has to be binary. There for I addeed a parseHex function and a Change to ignore already AES decrypted data. Normaly the flag "cw_parts.mode" woud be 0 not 5. New version 0.1.1.

If the data were not AES decoded (and you have set the key), it would probably have worked before.
However, you have to add a '4E'prefix. Here's an example:

```
var wmb = new WMBUS( {
    log: {
        debug: function () {}, //console.log,
        error: console.log
    }
});
wmb.crcRemoved = true;
//wmb.addAESKey(/* id */ '00051713', /* aes-key */ '0000000000000000');
wmb.decrypted = 1;
var data = '44D3101317050050047AAF0030052F2F0C0600000000046D032C34250C13213300008C4013000000008C804013000000000B3B1300000B2D0000002F2F2F';
wmb.parseHex ('4E' + data);

wmb.datablocks.forEach(function (data) {
    console.log(JSON.stringify(data));
});
``´

Hope this will help you.

**Comment by 0x-Fede** [comment]
Hi,

Thanks!

Sorry, I am testing it but it gives me an error. Can you help me with the code please?

# node -v v6.9.2

# node wmbus.js
/Desktop/metering-wmbus/wmbus/node_modules/wm-bus/lib/wmbus-decoder.js:1616
    return WMBUS.parse (data);
                 ^

TypeError: WMBUS.parse is not a function
    at WMBUS.parseHex (/Users/fgredruello/Desktop/metering-wmbus/wmbus/node_modules/wm-bus/lib/wmbus-decoder.js:1616:18)
    at Object.<anonymous> (/Users/fgredruello/Desktop/metering-wmbus/wmbus/wmbus.js:13:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
MacBookAir:wmbus fgredruello$ cat wmbus.js 
var WMBUS = require('wm-bus').WMBUS;


#cat wmbus.js

var WMBUS = require('wm-bus').WMBUS;

var wmbus = new WMBUS( {
    log: {
        debug: function () {}, //console.log,
        error: console.log
    }
});
wmbus.crcRemoved = true;
//wmb.addAESKey(/* id */ '00051713', /* aes-key */ '0000000000000000');
wmbus.decrypted = 1;
var data = '44D3101317050050047AAF0030052F2F0C0600000000046D032C34250C13213300008C4013000000008C804013000000000B3B1300000B2D0000002F2F2F';
wmbus.parseHex ('4E' + data);

wmbus.datablocks.forEach(function (data) {
    console.log(JSON.stringify(data));
});

**Comment by soef** [comment]
Hi,

sorry, my mistake. I saw that before but don't make an update. Now an update is available. Version is 0.1.6.

Greetings

**Comment by 0x-Fede** [comment]
Thanks! 
It works!

**Comment by p-veres** [comment]
Hello guys,
could I kindly ask you for some guidance and help with getting the data from a meter very similar to the Sonometer from Danfoss?

I used an SDR and rtl-wmbus and got the following raw reading:

0x5e44a5118529646440047a1d705005a208ff0ad5b4c5fObb92c2ed3578cdfb499b35d88271c5d26b9a1332da1c839624727ac80e1e89716bbe4fef09312df77dab787cd119a177eae3514612d719467ad310817de85d8e91eb7eef09b9692c

I tried to run it with an AES decryption tool (the encryption key is 11 11 11 11 11 11 11 11), but with no obvious effect. It seems I never get any reasonable output.

Could you please have a look at this and help me out? Many thanks in advance.

Peter
